### ISSUE TITLE
Galaxy S7 기기에서 동작에 문제가 생김

### ISSUE THREAD

**Issue by jungjin0003** [snoopspy/rara#1]
[rara.log](https://github.com/user-attachments/files/15757978/rara.log)
libhook이 로드되어 있지 않은 상황임에도 package list가 나오지 않고 `Zygote::getState` 함수에서 `fgets return null` 에러가 발생

또한 Update 버튼을 눌렀을 때 자동으로 `libhookzygote.so` 파일이 `/system/lib` 경로로 복사되지 않음
![image](https://github.com/snoopspy/rara/assets/43538880/541eb58a-c479-4896-89e8-dfff705add90)
![Screenshot_20240610-160903](https://github.com/snoopspy/rara/assets/43538880/4a23a364-c363-4ac2-9512-d534d90dee68)
![Screenshot_20240610-161212](https://github.com/snoopspy/rara/assets/43538880/a4d60e70-33ca-48a8-b67f-f0c237214c0d)

**Comment by snoopspy** [comment]
su 명령어가 제대로 실행이 안된 것으로 보임. 다음 2개 사항 확인해 주세요.

1. Settings > Developer Options > Root access 에서 "Apps and ADB" 선택.
![image](https://github.com/snoopspy/rara/assets/4080232/8ea33bae-85cd-4cfd-ac28-6094b36c5f5b)

2. 아래 화면에서 Remember my choice 선택해 주고 ALLOW 버튼 눌러야 함.
![image](https://github.com/snoopspy/rara/assets/4080232/f7072be6-2ede-4813-8e2b-5b98ceeb3921)

**Comment by jungjin0003** [comment]
"Apps and ADB"로 선택되어 있습니다. 그런데 앱을 실행할 때 Privacy Guard 알림은 뜨지 않네요?

**Comment by snoopspy** [comment]
Update 버튼을 누르면 다음 3가지가 실행이 되는데 몇 번까지 실행 성공했는지 확인해 보세요. 1, 2번은 성공했는데 3번이 안된다면 이것도 권한 문제임.
1. github에서 zip 파일 다운
2. zip 파일 압축 해제.
3. system 폴더에 libhook*.so 파일 복사.

**Comment by jungjin0003** [comment]
3번을 제외하고 모두 성공했습니다

**Comment by snoopspy** [comment]
그럼 권한 문제임. Privacy Guard 경고창 안 뜬 것과 상관 있는 것 같은데...
Settings > Privacy > Privacy Guard > R.A.R.A 오래 누르면 다음과 같은 창이 보이는지 확인해 보세요.
![image](https://github.com/snoopspy/rara/assets/4080232/2b747f1f-05fe-40c5-ac74-77db2f1133ef)

**Comment by jungjin0003** [comment]
Root access는 뜨지 않습니다
![Screenshot_20240610-165538](https://github.com/snoopspy/rara/assets/43538880/d96c1a44-a86f-460d-bfdb-d397986df9be)

**Comment by snoopspy** [comment]
나랑 화면이 좀 다르네... 
https://github.com/snoopspy/rara/assets/4080232/8d37e196-6180-485a-bcd0-522a6ee3e0a1

프로그램 삭제(adb uninstall kr.crazyhacker.rara)하고 재설치 한 다음 Privacy Guard 다시 한번 확인해 주세요.

**Comment by jungjin0003** [comment]
저는 아예 앱을 실행할 때 root access를 허용하겠냐는 알림창이 뜨지 않아요

**Comment by snoopspy** [comment]
그래도 다른 루팅 관련 앱들은 제대로 실행이 잘 되나?

**Comment by jungjin0003** [comment]
지금 확인을 해보니 termux에서도 su 커맨드가 먹히지 않네요

**Comment by snoopspy** [comment]
ADB에서는 su가 작동하는데 App에서는 su가 작동하지 않는 스마트폰의 문제로 파악되었습니다. issue close합니다.
