### ISSUE TITLE
libhookzygote.so가 로드되어 있는 상태에서 Unload 버튼이 비활성화 되어 있는 문제

### ISSUE THREAD

**Issue by jungjin0003** [snoopspy/rara#2]
다음 사진처럼 libhookzygote.so 파일이 zygote에 로드되어 있는데 Unload 버튼이 비활성화 되어 있는 경우가 있습니다. 확인부탁드립니다!
![Screenshot_20240610-183644](https://github.com/snoopspy/rara/assets/43538880/839b29f2-457d-4e5f-8a9d-78b9713b463c)

**Comment by snoopspy** [comment]
관련된 버그 수정하였는데 지금도 이러한 현상이 발생하고 있나요? 혹시 계속해서 발생하고 있다면
1. rara.log 파일을 지운다.
2. 앱을 실행한다.
3. 메인화면에서 버튼 활성화 상태를 확인한다.

계속해서 이러한 현상이 발생하는 경우 3번까지 진행하고 나서 rara.log 파일을 올려 주시기 바랍니다.

**Comment by jungjin0003** [comment]
해결됐습니다!

**Comment by snoopspy** [comment]
Update를 한번도 누르지 않아 zip파일을 다운받은 상황이 아니라면 저렇게 나올 수는 있음.

**Comment by jungjin0003** [comment]
참고하겠습니다!
